### ISSUE TITLE
Objects disappear if Depth Priming is not set to "Disabled"

### ISSUE THREAD

**Issue by daneobyrd** [ColinLeung-NiloCat/UnityURPToonLitShaderExample#11]
In an existing project and a blank project I just created for testing, the shader does not work as intended.

Currently it is behaving like this:

```
┌────────────────────┬──────────────────────────┐
│ Depth Priming Mode │       Visibility         │
├────────────────────┼──────────────────────────┤
│ Disabled           │ Scene & Game Window      │
│ Auto               │ Game Window Only         │
│ Forced             │ Only shadows are visible │
└────────────────────┴──────────────────────────┘
```

You can see a video of this [here](https://youtu.be/MS4XtbK7B-w).

Both projects/scenes have identical camera settings, post-processing, and URP Asset settings. Both projects shown have Light Layers enabled.

**Unity Version:** 2021.2.7f1
**URP Version:** 12.1.2

**Comment by umbad** [comment]
![라이트맵](https://user-images.githubusercontent.com/50651748/152154035-9a02832d-cd7f-4978-b5e9-d00b3505a778.PNG)
Pink in the shadow area. How did you do it? Is it a light map?

**Comment by ColinLeung-NiloCat** [comment]
We will review this shader again once Unity 2021.3 LTS is released, then we will support any new URP features(URP11/URP12) if needed.

**Comment by daneobyrd** [comment]
No that URP 2021.3 LTS is released, is this going to be revisited?

**Comment by daneobyrd** [comment]
This thread about the use of the depth prepass has been updated recently with the discussion from someone at Unity and some asset store developers:

https://forum.unity.com/threads/need-clarification-on-urps-use-of-the-depth-prepass.1004577/
