### ISSUE TITLE
wow

### ISSUE THREAD

**Issue by umbad** [ColinLeung-NiloCat/UnityURPToonLitShaderExample#12]
![라이트맵](https://user-images.githubusercontent.com/50651748/152154289-c1412549-c82c-445e-afab-3267444a20b8.PNG)
Pink in the shadow area. How did you do it? this is beauti!!!
Is it a light map?

**Comment by ColinLeung-NiloCat** [comment]
not related to lightmap, it is realtime shadow

**Comment by umbad** [comment]
> 
realtime??? really? wow.... 
I didn't know unity had that function.
That's amazing.
Can you tell me how to do it?

**Comment by ColinLeung-NiloCat** [comment]
if you get the Light.shadowAttenuation in shader (hlsl code), you can do any color edit based on the value of  Light.shadowAttenuation
