### ISSUE TITLE
Getting some "Couldn't open include file..." errors With 2021.3.33

### ISSUE THREAD

**Issue by cancaglar** [ColinLeung-NiloCat/UnityURPToonLitShaderExample#16]
First of all, thank you very much for sharing these. Actually, I used these shaders before, and now when I want to use them again, I encountered these errors. I tried to research and fix them, but I couldn't manage. I checked if the relevant files were removed from the mentioned repository, but I couldn't find a solution because I'm not very knowledgeable about shaders. How can this issue be resolved?

Version : 2021.3.33f URP
Platform : Windows 10

![image](https://github.com/ColinLeung-NiloCat/UnityURPToonLitShaderExample/assets/59360242/93e4ed7b-0f39-4565-b151-d210476bcfac)

**Comment by ColinLeung-NiloCat** [comment]
the minimum unity version is Unity2022.3 now

**Comment by Prsaro** [comment]
Same error with version 2022.3.43f1c1, MacOS
![image_1cf0724d-56ce-42c3-95c2-634d4324fa46](https://github.com/user-attachments/assets/b5101134-1adb-4972-b7ce-d4de994999a9)

**Comment by ColinLeung-NiloCat** [comment]
you can check your package manager, see if URP is installed
