### ISSUE TITLE
how do you change the outline so it doesn't change with object scale?

### ISSUE THREAD

**Issue by laurentopia** [ColinLeung-NiloCat/UnityURPToonLitShaderExample#4]
I tried this but that doesn't work

`return 10*normalize(input.positionOS + outlineNormalOSUnitVector) * _OutlineWidth; //you can replace it to your own method! Here we will use the most simple method for tutorial reason, it is not the best method!
`

**Comment by ColinLeung-NiloCat** [comment]
first you convert positonOS to positionWS
and convert normalOS to normalWS,
then use positionWS + normalize(normalWS) * _OutlineWidth

**Comment by ColinLeung-NiloCat** [comment]
I have updated the shader to use world space outline width
