### ISSUE TITLE
shader编译错误

### ISSUE THREAD

**Issue by czy-moyu** [ColinLeung-NiloCat/UnityURPToonLitShaderExample#5]
![image](https://user-images.githubusercontent.com/45380309/97066732-6a9aea00-15ea-11eb-9e04-dcd36b4a57fc.png)

**Comment by czy-moyu** [comment]
Unity版本 2019.4.9f1,URP版本7.3.1

**Comment by ColinLeung-NiloCat** [comment]
try reimport the shader

**Comment by ColinLeung-NiloCat** [comment]
I tested the shader with different editor versions, it should compile correctly.
If you encounter this bug again, please open a new issue, thank!
