### ISSUE TITLE
Shader error

### ISSUE THREAD

**Issue by iloveyehan** [ColinLeung-NiloCat/UnityURPToonLitShaderExample#8]
shader error in 'SimpleURPToonLitExample(With Outline)': undeclared identifier 'AdditionalLightShadow' at Assets/UnityURPToonLitShaderExample-master/SimpleURPToonLitOutlineExample_Shared.hlsl(354) (on d3d11)
![image](https://user-images.githubusercontent.com/79322035/108567072-78673e80-7342-11eb-845d-fded09e60bd2.png)

**Comment by ColinLeung-NiloCat** [comment]
hello, which unity version and URP version are you using?

**Comment by iloveyehan** [comment]
I use unity 2020.1.6f1c1 personal <dx11>

**Comment by iloveyehan** [comment]
![image](https://user-images.githubusercontent.com/79322035/108589754-eccdcc00-739a-11eb-9e2e-96abeb5f4179.png)
2019.4LTS also show this error

**Comment by ColinLeung-NiloCat** [comment]
thanks, fixed
