### ISSUE TITLE
Anti-Aliasing causes emulator/PC-Quality Demo to run at 1 FPS

### ISSUE THREAD

**Issue by daneobyrd** [ColinLeung-NiloCat/UnityURPToonLitShaderExample#9]
When quality slider is set to emulator/PC, the demo runs at a maximum of 1 FPS in all situations except when I turn anti-aliasing off in the "check" scene featuring Klee and Ganyu.

[Screen Recording 1](https://youtu.be/yXGhqNqTdmw)
[Screen Recording 2](https://youtu.be/sRz0tqpv2W0) - Less stuttering
Screen recording is done with OBS. The AA at emulator/PC quality taxes my GPU enough that it causes stuttering in my recording. I tried to optimize my encoding settings and uploaded a second screen recording that I hope is helpful. You can notice the recording stutter when my mouse jumps to a new position suddenly. My mouse was moving smoothly across the screen when I recorded this.

My specs as shown in the debug UI are:

> OS: Windows 10 (10.0.19042) 64bit [WindowsPlayer]
> CPU: AMD Ryzen 7 3700X 8-Core Processor [16 Cores]
> GPU: NVIDIA GeForce GTX 1660 SUPER
> GPU: Direct3D 11.0 [level 11.1] [Direct3D11]
> GPU: SM: 5.0, VRAM: 5991 MB
> RAM: 16292 MB
> SCR: 3840x2160@60Hz [window size: 3840x2160, DPI: 144]
> Model: System Product Name (ASUS)

**Comment by ColinLeung-NiloCat** [comment]
We tried applying a quick fix to solve the anti-aliasing fps problem, by limit maximum resolution to 1080p.
https://drive.google.com/file/d/1MubGDhlDRKKxR9xyl7fcLyECyBJdsqrI/view?usp=sharing
 
if you could help us to test the new version (test if the new version still having 1fps problem or not), we would highly appreciate it!

**Comment by daneobyrd** [comment]
Looks great! No issues with the anti-aliasing.
One small note: When you click away to another program (I have a second monitor) and then click back to the demo, FPS drops down to 30 or even 0 for less than a second, then returns to ~60.

> FPS: 60 [16.66 MS]
> AVG: 57 [17.54 MS]
> MIN:0 MAX: 60
> MEM TOTAL: 466.51 MB
> MEM ALLOC: 363.03 MB
